---
# yamllint disable rule:line-length
name: Installer test
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - .github/workflows/installer-test.yml
jobs:
    installer-test:
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10", "3.11"]
                os: [ubuntu-20.04. ubuntu-22.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Run installer
              run: |
                set -euxo pipefail
                wget -O /tmp/installer.py "https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=en&profile=523&device=linux&generatedfor=user&openroaming=0"
                mkdir -p ~/.virtualenvs
                python3 -m venv ~/.virtualenvs/eduroam-installer
                source ~/.virtualenvs/eduroam-installer/bin/activate
                python3 -m pip install dbus-python
                python3 /tmp/installer.py
